### ISSUE TITLE
Review Paper #2 

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL-2020#3]
@kfenlon + @akthom  review paper https://github.com/sig-cm/JCDL-2020/blob/master/jcdl_20_gryk_ludaescher.pdf 

- [x] Overview (2-3 sentence overview of the contribution)
- [x] Feedback (2-3 paragraphs highlighting strengths of the paper. Please note anything that will be valuable for the authors to discuss / present at workshop)

**Comment by organisciak** [comment]
This submission probes the Which One Doesn't Belong game from the perspective of items that are unique in not being unique. This seems like the 'Star Wars' of problems - a film that is derivative, but uniqueless exciting in its mix of borrowings.

The approach is refreshing and should promote a healthy discussion. Still, I would encourage more consideration of how this exercise may potentially help in considering conceptual models more broadly; if 'some are useful', how is this one useful?

An intriguing direction that might bear exploring further is the unraveling of the 'trick'. It's clever how you boil it down to a XOR, but I don't think it actually needs to be binary categories. It would require many more items to demonstrate, but if we looked at gold/silver/pewter small/medium/large pots with 0/1/2 handles, you could still end up with the unique in being non-unique situation.
This situation opens many new discussions, and I'd love to see some consideration of the complications it introduces. 

The other consideration worth exploring more is the paradox of the item that is uniquely non-unique - does it becoming unique not nullify it's uniqueness? Is there an inherent assumption that non-unique uniqueness is a higher-priority form of 'uniqueness'? And how does this square with the consideration of properties individually - if both the blue circle and blue square are unique in their combinations but the blue circle is the correct answer because it's the only one unique in a specific property (shape), why do we get to treat the non-unique item through the sum of its parts?

Typo: the last line should end with a question mark, right?

**Comment by organisciak** [comment]
Well shoot, I didn't realize that I wasn't assigned to this.

**Comment by karenwickett** [comment]
I would love to hear more from the authors about how this kind of conceptualization plays out in (something like) a retrieval system. For example, it is commonly assumed that classification categories are mutually exclusive and complete, and we use this assumption in building a retrieval system. Then when we process queries based on those categories, we feel good about the results, since we should be seeing everything that could be in each category. Some questions: 
1. How does the "binary trick" play out in those scenarios from the point of view of a retrieval system? How does it relate to denormalization strategies or schema-free modeling for large-scale databases?
2. Does this kind of binary refactoring work for all kinds of properties? How does it relate to the practice of "digitalization" commonly seen in visual data (where portions of a map or image are associated with certain categories)? 
3. What kinds of data modeling design guidelines might arise from this analysis? Can we recommend modeling strategies that will let us detect unique objects?
